Fix linking of libmultiplexer.so
zbyszek@ubuntu-1140:~/eeg/azouk-libraries$ (cd; python -c 'from multiplexer import mxclient')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/multiplexer/mxclient.py", line 23, in <module>
    from azouk._allinone import *
ImportError: /usr/local/lib/libmultiplexer.so.0: undefined symbol: _ZN5boost7signals6detail14named_slot_map5beginEv

Before this change, linking with g++-4.6 worked fine in Debian,
but not in Ubuntu oneiric. This means that this is not gcc related,
and depends on something else. But the fix is pretty clear, so let's
do it.