Use BOOST_PYTHON_MODULE again
Otherwise the name of the init function doesn't match the file name.
>>> import _mxclient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (init_mxclient)